import Head from 'next/head'
import styles from '../styles/Home.module.css'
import 'animate.css';
import AsyncSelect from "react-select/async";
import Select, {SingleValue} from "react-select";
import React, {useId, useState} from "react";
import {getCountryName, searchQuery} from "../helpers";
import {countryCodeEmoji} from "country-code-emoji";

export default function Home() {
    const [value, setValue] = useState<object|null>(null)

    const [countryValue, setCountryValue] = useState<object|null>(null)
    const [countryOpts, setCountryOpts] = useState<Array<unknown>>([])

    return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={"animate__animated animate__fadeIn"}>
          Where Can I Watch?
        </h1>

        <div className={styles.selectContainer}>
            <AsyncSelect
                loadOptions={(input) => {
                    return searchQuery(input).then((r: any) => r.data)
                }}
                instanceId={useId()}
                className={"animate__animated animate__fadeInLeft"}
                getOptionLabel={(item: any) => (item.title || item.name)}
                getOptionValue={(item: any) => item.id}
                styles={{
                    container: () => ({
                        width: "400px",
                        fontSize: "18px"
                    })
                }}
                onChange={(item: SingleValue<object>) => {
                    setValue(item || {})
                    searchQuery(item || {}).then((res: any) => setCountryOpts(res.data))
                }}
                value={value}
                placeholder={"Search the movie..."}
                menuPlacement={'bottom'}
                menuPosition={'fixed'}
            />
            <Select
                isSearchable={false}
                isDisabled={!Boolean(Object.keys(countryOpts).length)}
                options={Object.keys(countryOpts).map((item: string) => {
                    return {
                        label: `${getCountryName(item)} ${countryCodeEmoji(item)}`,
                        value: item
                    }
                })}
                onChange={(item) => {
                    setCountryValue(item || {})
                }}
                value={countryValue}
                instanceId={useId()}
                className={"animate__animated animate__fadeInRight"}
                styles={{
                    container: () => ({
                        width: "300px",
                        fontSize: "18px"
                    }),
                    menu: () => ({
                        width: '300px',
                        backgroundColor: '#ffffff'
                    })
                }}
                placeholder={"Country..."}
                menuPlacement={'bottom'}
                menuPosition={'fixed'}
             />
        </div>

      </main>
    </div>
  )
}
